services:
  pyapi:
    build:
      context: ../../
      dockerfile: ./docker/dev/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ../../src:/app/src
    environment:
      - AUTH_USER=admin
      - AUTH_PASS=admin
